### ISSUE TITLE
Please help me make a cryptonote fork

### ISSUE THREAD

**Issue by doubleconnect1** [LetheanMovement/lethean#109]
I got the following errors. 
I installed gcc of the following version. 
Please help me. 
--------------------------------------------------------------------------------------------------
daeyeonjo@daeyeonjo-All-Series:~/nowcoin$ gcc --version | head -n1
gcc (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
-------------------------------------------------------------------------------------------------
daeyeonjo@daeyeonjo-All-Series:~/nowcoin$ make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Found Git: /usr/bin/git
CMake Warning in CMakeLists.txt:
  CMAKE_SKIP_INSTALL_RULES was enabled even though installation rules have
  been specified

-- Configuring done
-- Generating done
-- Build files have been written to: /home/daeyeonjo/nowcoin/build/release
cd build/release && make
make[1]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[2]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
fatal: 이름이 없습니다. 아무것도 설명할 수 없습니다.
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.

make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
[  0%] Built target version
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
[  5%] Built target upnpc-static
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
[  6%] Built target gtest
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
[  6%] Built target gtest_main
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
[  9%] Built target Serialization
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
[ 11%] Built target Http
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
Scanning dependencies of target Common
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
[ 11%] Building CXX object src/CMakeFiles/Common.dir/Common/Util.cpp.o
[ 11%] Linking CXX static library libCommon.a
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
[ 18%] Built target Common
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 들어감

[ 18%] Building CXX object src/CMakeFiles/System.dir/Platform/Linux/System/TcpConnection.cpp.o
/home/daeyeonjo/nowcoin/src/Platform/Linux/System/TcpConnection.cpp: In member function ‘size_t System::TcpConnection::read(uint8_t*, size_t)’:
/home/daeyeonjo/nowcoin/src/Platform/Linux/System/TcpConnection.cpp:71:26: error: logical ‘and’ of equal expressions [-Werror=logical-op]
     if (errno != EAGAIN  && errno != EWOULDBLOCK) {
                          ^
/home/daeyeonjo/nowcoin/src/Platform/Linux/System/TcpConnection.cpp: In member function ‘std::size_t System::TcpConnection::write(const uint8_t*, size_t)’:
/home/daeyeonjo/nowcoin/src/Platform/Linux/System/TcpConnection.cpp:167:26: error: logical ‘and’ of equal expressions [-Werror=logical-op]
     if (errno != EAGAIN  && errno != EWOULDBLOCK) {
                          ^
cc1plus: all warnings being treated as errors

src/CMakeFiles/System.dir/build.make:326: recipe for target 'src/CMakeFiles/System.dir/Platform/Linux/System/TcpConnection.cpp.o' failed
make[3]: *** [src/CMakeFiles/System.dir/Platform/Linux/System/TcpConnection.cpp.o] Error 1
make[3]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
CMakeFiles/Makefile2:600: recipe for target 'src/CMakeFiles/System.dir/all' failed
make[2]: *** [src/CMakeFiles/System.dir/all] Error 2
make[2]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
Makefile:94: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: 디렉터리 '/home/daeyeonjo/nowcoin/build/release' 나감
Makefile:20: recipe for target 'build-release' failed
make: *** [build-release] Error 2

**Comment by pallas1** [comment]
It is a warning threated as error.
Look here:
https://stackoverflow.com/questions/11561261/how-to-compile-without-warnings-being-treated-as-errors

**Comment by valiant1x** [comment]
Sorry, this is not the place to support forks. Try a CryptoNote/general Monero message board or IRC chat.
