### ISSUE TITLE
daemon CPU usage 100%

### ISSUE THREAD

**Issue by pcca-matrix** [LetheanMovement/lethean#111]
it's been several days my daemon is in trouble on my pool , 16 cores cpu at 100% !
print_pool_stats show sometime 40-50 tx inside  
i must use flush_txpool or restart daemon to fix.

there is a problem with the network?

**Comment by pcca-matrix** [comment]
already disabled but it does not fix

**Comment by pallas1** [comment]
try connecting to a fixed set of other nodes you trust.
for example the seednodes, other trusted pools, etc.
let me know if that fixes.

**Comment by pcca-matrix** [comment]
connected to a single node and it seems to be better no more cpu overload for now (1hours) ! 
I let it for a few hours and I give the result later
Thanks

**Comment by pallas1** [comment]
Thanks. The pool performance (orphans percent) may degrade with just one peer.

**Comment by pcca-matrix** [comment]
it seems that it works, with 3 exclusive trusted nodes !
if  i remove exclusive mode, after few hours cpu usage is around 70-100%
You can close issue 
Thanks
