### ISSUE TITLE
simplewallet cross compilation issue - missing uint64 on ARM

### ISSUE THREAD

**Issue by limosek** [LetheanMovement/lethean#114]
Simplewallet could be run on small machine like rpi but there is problem with crosscomoilation on ARM devices because uint64 is missing.
I solved and compiled working binaries by adding this line in src/crypto/slow-hash.c:
`
#ifdef __ARM_ARCH_7__
#define uint64 unsigned long long
#endif
`
and compiled in multi-arch within ubuntu:
cmake  -Bbuild-armv7 -H. -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_IGNORE_PATH=/usr/lib/x86_64-linux-gnu -DARCH=armv7 -DSTATIC=ON

**Comment by pallas1** [comment]
the patch is ok for me; just to be sure, I would surround it by an "#ifndef uint64"
wanna PR?

**Comment by limosek** [comment]
Yes, my fault, #ifndef uint64 is definitely needed.
And there will be probably more ARM versions needed in ifdef. Probably V6 and V7
Thank you!

**Comment by valiant1x** [comment]
fixed in #130
