### ISSUE TITLE
Apply new Monero PoW algo CNv2

### ISSUE THREAD

**Issue by pallas1** [LetheanMovement/lethean#123]
Hard fork to the new proof of work algorithm to be in line with monero and enhance ASIC/FPGA resistance.

Should be a matter of applying:

https://github.com/monero-project/monero/commit/5fd83c13fbf8dc304909345e60a853c15b0de1e5#diff-7000dc02c792439471da62856f839d62

plus:

https://github.com/monero-project/monero/commit/f3cd51a12b202875bd8191668aceb8a4f810ecd4#diff-7000dc02c792439471da62856f839d62

and setting hardfork data.

**Comment by Venthos** [comment]
For pool support, note that this repo/branch needs to be updated in tandem:

https://github.com/valiant1x/node-cryptonote-util/commits/xmr-Nan-2.0
(Perhaps relocate to LetheanMovement github user, too?)

Pools running on nodejs-pool (mine, official pool, etc) would need that working.

I already support CNv2 via my branch of node-cryptonight-hashing which is the other bit that nodejs-pool needs.

https://github.com/Venthos/node-cryptonight-hashing

So no issues there.

**Comment by valiant1x** [comment]
Fork is complete, closing issue.
