### ISSUE TITLE
Wallet Error when 16-Hex (8 byte) payment ID is used on CLI wallet when trying multiple address transfer

### ISSUE THREAD

**Issue by yanuarsu2201** [LetheanMovement/lethean#148]
Lethean-Cli wallet error when trying multiple address transfer using 8-byte (encrypted) payment ID. Possible it happens on RPC also.

**Comment by valiant1x** [comment]
This is a protocol limitation due to the fact that the encrypted payment ID is a singular field in a TX. [more info](https://monero.stackexchange.com/questions/8452/sending-monero-to-multiple-integrated-address)
