### ISSUE TITLE
Error when compiling on Arch Linux

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean#151]
I get following error when compiling on Arch Linux

`/home/lethe/lethean/src/cryptonote_basic/miner.cpp: In member function ‘bool cryptonote::miner::background_worker_thread()’:
/home/lethe/lethean/src/cryptonote_basic/miner.cpp:671:24: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in assignment
         on_ac_power = !battery_powered;`

**Comment by ronnylov** [comment]
Found that Monero have the same issue.
https://github.com/monero-project/monero/issues/4695

**Comment by ronnylov** [comment]
They fixed it for Monero?
https://github.com/monero-project/monero/pull/4700

**Comment by valiant1x** [comment]
fix PR was merged, issue should be resolved. please tag me @valiant1x if this needs to be reopened.
